version = 0.1
[default.deploy.parameters]
stack_name = "telemetry-service"
resolve_s3 = true
s3_prefix = "telemetry-service"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
